services:
  postgres:
    image: postgres:16
    container_name: trans_db
    restart: always
    environment:
      POSTGRES_USER: translogix
      POSTGRES_PASSWORD: qwerty007
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
volumes:
  postgres_data: